use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
cpan
Chris
Prather
chris
Stevan
Little
stevan
יובל
קוג
Yuval
Kogman
nothingmuch
Infinity
Interactive
Inc
Cory
Watson
gphat
Dagfinn
Ilmari
Mannsåker
ilmari
Dan
Brook
dan
David
Golden
dagolden
Steinbrunner
dsteinbrunner
Florian
Ragwitz
rafl
Johannes
Plunien
plu
Jonathan
Rockway
jon
Yu
frequency
Jos
Boumans
jos
Karen
Etheridge
ether
Ricardo
Signes
rjbs
Robert
Boone
robo4288
Shawn
Moore
sartak
Tomas
Doran
bobtfish
lib
MooseX
Storage
IO
AtomicFile
StorableFile
Traits
DisableCycleDetection
Meta
Attribute
Trait
DoNotSerialize
Engine
OnlyWhenBuilt
File
Basic
Deferred
Base
WithChecksum
Util
Format
JSON
Storable
YAML
