use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
cpan
Chris
Prather
chris
Stevan
Little
stevan
Yuval
Kogman
yuval
Infinity
Interactive
Inc
lib
MooseX
Storage
IO
File
Util
Engine
Trait
DisableCycleDetection
Format
JSON
Meta
Attribute
DoNotSerialize
OnlyWhenBuilt
AtomicFile
Deferred
Base
WithChecksum
Traits
YAML
StorableFile
Storable
Basic
